# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  uefi-build:
    cmds:
      - cargo build --target x86_64-unknown-uefi
      - cp target/x86_64-unknown-uefi/debug/wasabi.efi mnt/EFI/BOOT/BOOTX64.EFI
  uefi-run:
    cmds:
      - qemu-system-x86_64 -bios third_party/ovmf/RELEASEX64_OVMF.fd -drive format=raw,file=fat:rw:mnt
  clippy:
    cmds:
      - cargo clippy
  lscpu:
    cmds:
      - system_profiler SPHardwareDataType
